"""Wallet address

Revision ID: 6cb05620b4bd
Revises: 1010ddb40ed1
Create Date: 2024-12-28 22:31:26.275593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb05620b4bd'
down_revision: Union[str, None] = '1010ddb40ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tronwallets', sa.Column('address', sa.String(length=255), nullable=False))
    op.alter_column('tronwallets', 'balance',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_tronwallets_address'), 'tronwallets', ['address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_tronwallets_address'), 'tronwallets', type_='unique')
    op.alter_column('tronwallets', 'balance',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('tronwallets', 'address')
    # ### end Alembic commands ###
